---
language: python
services: docker

env:
  global:
    - ROLE_NAME: zfs
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: fedora29

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME hwwilliams.$ROLE_NAME
  - cd hwwilliams.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
