---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update Apt Cache
      apt: update_cache=yes cache_valid_time=360
      when: ansible_os_family == 'Debian'
      changed_when: false
  roles:
    - role: hwwilliams.zfs
  tasks:
    - name: Check If ZFS Is Installed
      shell: zfs --help
      register: zfs_available
      failed_when: zfs_available.rc != 0
      changed_when: false